<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYQkqx9M\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYQkqx9M/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYQkqx9M.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYQkqx9M\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerYQkqx9M\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'YQkqx9M',
    'container.build_id' => 'f310fcde',
    'container.build_time' => 1551222488,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYQkqx9M');
